package:
  name: galibrate
  version: "0.7.1"

source:
  git_url: https://github.com/blakeaw/GAlibrate.git
  git_rev: v0.7.1

requirements:
  build:
    - python >=3.10
    - setuptools >=66.0.0

  run:
    - python >=3.10.11
    - numpy >=1.23.5
    - scipy >=1.10.1

build:
  noarch: python
  script: python setup.py install
  include_recipe: False

test:
  imports:
    - galibrate

about:
  home: https://github.com/blakeaw/GAlibrate
  license: MIT
  license_file: LICENSE
  summary: "Model calibration using Genetic Algorithm optimization in Python."